services:
  my_jenkins:
    image: jenkins/jenkins:lts
    user: root
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ylohith/.kube:/root/.kube
    network_mode: host

volumes:
  jenkins_data:
