version: '3.8'

services:
  my_jenkins:
    image: jenkins/jenkins:lts
    user: root
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/kanupr/.kube:/root/.kube
      - /home/kanupr/.minikube:/root/.minikube
    network_mode: host

volumes:
  jenkins_data:
