apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/ylohith/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Wed, 08 Oct 2025 16:48:40 UTC
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    server: https://127.0.0.1:32781
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/ylohith/.minikube/profiles/minikube/client.crt
    client-key: /home/ylohith/.minikube/profiles/minikube/client.key

